name: Release
on:
  release:
    types: [published]

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    uses: ./.github/workflows/_job_build.yml
    with:
      name: ${{ github.ref_name }}
  upload:
    needs: build
    uses: ./.github/workflows/_job_upload.yml
    with:
      version: ${{ github.ref_name }}
      name: ${{ github.ref_name }}